# Site Settings
# These settings affect how your site appears and functions
title: "and now, we drift"
description: >-
  on the winds, the time, the faith, and the stars.

# CRITICAL: URL Configuration for GitHub Pages
# Since this is a project site (not username.github.io), we need baseurl
url: ""  # This will be set automatically by GitHub Pages
baseurl: "/ChainOfNoThought"  # MUST match your repository name exactly

# Language and timezone settings
lang: "en"
timezone: "Etc/GMT-4"  # Timezone (Note: Etc/GMT zones use inverted signs)

# Build settings
markdown: kramdown  # Only markdown processor supported by GitHub Pages
theme: minima       # Simple, clean theme perfect for writing

# Only use GitHub Pages whitelisted plugins
# See: https://pages.github.com/versions/
plugins:
  - jekyll-seo-tag     # Adds meta tags for better SEO
  - jekyll-sitemap     # Generates sitemap.xml for search engines

# Files and directories to exclude from build
# This improves build performance
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .bundle/
  - node_modules/
  - docs/          # Documentation directory
  - scripts/       # Build and maintenance scripts
  - README.md      # Repository documentation
  - "*.sh"         # Shell scripts

# Permalink structure for thoughts (essays)
# This creates clean URLs like /2024/01/15/my-thought/
permalink: /:year/:month/:day/:title/

# Enable strict front matter validation
# This helps catch errors during development
strict_front_matter: true

# Collections for organizing different types of writing
collections:
  # Essays/thoughts collection
  thoughts:
    output: true
    permalink: /thoughts/:title/
  
  # Stories collection with support for chapters
  stories:
    output: true
    permalink: /stories/:path/

# Default values to avoid repetition
defaults:
  # Default layout for all pages
  - scope:
      path: ""
    values:
      layout: "default"
  
  # Specific defaults for thoughts/essays
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: "post"
      author: "ChainOfNoThought"  # Change this to your name
      category: "thoughts"
  
  # Defaults for stories
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "post"
      category: "stories"

# Minima theme configuration
# Keep it simple and readable
minima:
  # Date format for posts
  date_format: "%B %-d, %Y"  # e.g., "January 15, 2024"
  
  # Social links (optional, remove if not needed)
  # social_links:
  #   twitter: your_username
  #   github: your_username

# Navigation menu
# List the pages you want in your site navigation
header_pages:
  - thoughts.md
  - stories.md
  - prosterity.md
  - about.md

# Future-proofing
future: true  # Publish posts with future dates

# Footer text
footer_text: "and now, we drift" 